name: test
on: 
  pull_request:
    branches:
      - develop
    types: [closed]


jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: github.event.pull_request.merged == true
    steps:
      - run: gh repo clone $GITHUB_REPOSITORY . --  --branch ${GITHUB_REF#refs/heads/}
      - run: cd $GITHUB_REPOSITORY
      - run: gh pr create --title "PR to staging" --body "testing"
    

